import SideBar from "@/components/SideBar";
import "./globals.css";

export const metadata = {
  title: "MY APPS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex antialiased">
        <SideBar />
        <div className="ml-2 mt-1 bg-radial from-green-300 via-yellow-200 to-blue-300 min-w-[85%] rounded-md h-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
